version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: postgres:9.6
        environment:
          POSTGRES_USER: nomnom
          POSTGRES_PASSWORD: password
          POSTGRES_DB: nomnom


    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx2000m
      CIRCLE: "yep"
      PG_USER: nomnom
      PG_PASSWORD: password
      PG_DB: nomnom
      PG_HOST: localhost

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name:  run tests
          command: |
            ./script/ci-test
